#!/bin/sh

# ==============================================================================
# no_commit
# ==============================================================================
BLOCK_MARKER="no_commit"

echo "Checking for no_commit..."
if git diff --cached --diff-filter=ACM | grep -F @"$BLOCK_MARKER"; then
    echo "❌ Commit blocked: Found @$BLOCK_MARKER in staged changes."
    exit 1
fi

# ==============================================================================
# Build
# ==============================================================================
echo "Checking build..."
if ! jai -quiet ./build.jai; then
    echo "❌ Commit blocked: Build failed."
    exit 1
fi

exit 0
